Fibonocci code is updated
dineshN52/Training1 pull request #1
Opened 2023-08-18 12:18 UTC by dineshN52

2023-08-21 04:11 UTC, ravin-imm requested changes

2023-08-21 04:11 UTC, ravin-imm commented on Program.cs
> +            int n1 = 0, n2 = 1, n3, i, number;
Variable "i" can be initialized in _for_ loop itself.  Try to add simple comments to what each variable stores.

2023-08-21 04:11 UTC, ravin-imm commented on Program.cs
> +            {
No need to leave a separate line for "{" braces. I think VS 2022 is not configured. Please configure it using the settings that was shared earlier.

2023-08-21 10:19 UTC, dineshN52 commented on Program.cs
> +            int n1 = 0, n2 = 1, n3, i, number;
changed the initialization and updated sir

2023-08-21 10:20 UTC, dineshN52 commented on Program.cs
> +            {
VS is configured and change requested is performed and updated sir

2023-08-22 04:19 UTC, ravin-imm requested changes

2023-08-22 04:19 UTC, ravin-imm commented on Program.cs
> +         int n1 = 0, n2 = 1, n3, number; //n1 & n2 are input, n3 and number are temporary variable
"n3 and number are temporary variables" is not a meaningful comment. It doesn't describe what they hold.

2023-08-22 04:41 UTC, ravin-imm approved these changes

2023-08-23 04:36 UTC, closed without merging