T04
dineshN52/Training1 pull request #2
Opened 2023-08-18 12:25 UTC by dineshN52

2023-08-21 04:15 UTC, ravin-imm requested changes

2023-08-21 04:15 UTC, ravin-imm commented on Program.cs
> +            while (b != 0) {
The code is not formatted properly. Why another namespace?

2023-08-22 04:29 UTC, ravin-imm requested changes

2023-08-22 04:29 UTC, ravin-imm commented on Program.cs
> +         return (a * b) / gcd (a, b);
Methods/ functions names should start with a capital letter like Gcd (..)

2023-08-22 04:29 UTC, ravin-imm commented on Program.cs
> +         Console.WriteLine ($"GCD of {num1} and {num2} is {GCD}");
Can be simplified: 
_Console.WriteLine ($"LCM of {num1} and {num2} is {lcm (num1, num2)}")_

2023-08-22 04:29 UTC, ravin-imm commented on Program.cs
> +         }
No need of "{" and "}" brances as its only one line after the _if_ statement.

2023-08-22 05:04 UTC, dineshN52 commented on Program.cs
> +         }
Removed and code updated sir

2023-08-22 05:06 UTC, dineshN52 commented on Program.cs
> +         Console.WriteLine ($"GCD of {num1} and {num2} is {GCD}");
Removed the declaration and include the function in WriteLine itself sir

2023-08-22 05:06 UTC, dineshN52 commented on Program.cs
> +         return (a * b) / gcd (a, b);
Changed to capital Letter and updated sir

2023-08-23 04:04 UTC, ravin-imm approved these changes

2023-08-23 04:35 UTC, closed without merging