T20:Display individual digits
dineshN52/Training1 pull request #25
Opened 2023-09-22 11:49 UTC by dineshN52

2023-10-13 07:38 UTC, v-priya requested changes

2023-10-13 07:38 UTC, v-priya commented on Program.cs
> +            Printdigit (parts[1].ToCharArray ());//printing the factorial part
Instead of writing each character to the console, use `string.Join` to combine and print `Console.WriteLine ("Integral part digits are: {0}", string.Join (' ', parts[0].ToCharArray ()));`

2023-10-13 11:04 UTC, dineshN52 commented on Program.cs
> +         if (value.Contains ('.')) {
What if user entered whole number instead of a decimal number?

2023-10-16 14:01 UTC, v-priya requested changes

2023-10-16 14:01 UTC, v-priya commented on Program.cs
> +      static void Individualdigits (double number) {
Function name should convey what the function performs. For example: PrintDigits or DisplayDigits

2023-10-16 14:01 UTC, v-priya commented on Program.cs
> +            Console.WriteLine ("Factorial part digits are: {0}", string.Join (' ', parts[1].ToCharArray ()));
Have a separate function `Print` and use it to do the `Console.WriteLine`.  If there is repetitive code, check if they can be moved into a function.

2023-10-19 10:00 UTC, v-priya requested changes

2023-10-27 13:00 UTC, v-priya requested changes

2023-10-27 13:00 UTC, v-priya commented on Program.cs
> +      static void JoinDigits (string s, string prefix) => Console.Write ($"\n{prefix} digits are: {string.Join (' ', s.ToCharArray ())}");
Why is the function named `JoinDigits` instead of `Print`, when it is actually writing to the console? Also, why use `Console.Write` with `\n` when the same can be written with `Console.WriteLine`.

2023-10-30 06:13 UTC, v-priya commented on Program.cs
> +         string[] parts = number.ToString ().Split ('.'); //split input into two substrings(Integral and factorial part)
@dineshN52 Please ensure that there is a space between `//` and actual comment. Also, space should be there between `substrings` and `(Integral`. Make sure to follow this convention always.

2023-10-30 06:13 UTC, v-priya approved these changes

2023-10-30 06:14 UTC, closed without merging