T05
dineshN52/Training1 pull request #3
Opened 2023-08-21 03:19 UTC by dineshN52

2023-08-21 04:27 UTC, ravin-imm requested changes

2023-08-21 04:27 UTC, ravin-imm commented on Program.cs
> +               return true;
This is always false as the "num" can't be equal to 2 and 3 at the same time. Is this check required?

2023-08-21 04:27 UTC, ravin-imm commented on Program.cs
> +                  return false;
Instead of looping through till the number before, can you simplify this?

2023-08-21 04:27 UTC, ravin-imm commented on Program.cs
> +               Console.WriteLine ($"{number} is not a prime number.");
Check if you can use a single _Console.WriteLine (..)_ statement by changing the message depending on the check inside the _Console.WriteLine (..)_ statement itself.

2023-08-21 11:40 UTC, dineshN52 commented on Program.cs
> +               Console.WriteLine ($"{number} is not a prime number.");
Both condition is printed using single Console.Writeline function using ternary operator and code was updated sir

2023-08-21 11:41 UTC, dineshN52 commented on Program.cs
> +               return true;
As the comparison is not required it is removed and updated sir

2023-08-22 04:31 UTC, ravin-imm requested changes

2023-08-22 04:31 UTC, ravin-imm commented on Program.cs
> +            if (b % i == 0)
Can you simplify the loop count?

2023-08-22 06:17 UTC, dineshN52 commented on Program.cs
> +            if (b % i == 0)
Loop count reduced by creating loop condition with square of i ,by modular arithmetic b modulo i*i & b modulo i results same.

2023-08-23 04:07 UTC, ravin-imm requested changes

2023-08-23 04:07 UTC, ravin-imm commented on Program.cs
> +         Console.WriteLine (string.Concat ($"{a} is" , IsPrime (a) ? " a prime number" : " not a prime number"));
Try this out without string.Concat (..)

2023-08-23 04:33 UTC, dineshN52 commented on Program.cs
> +         Console.WriteLine (string.Concat ($"{a} is" , IsPrime (a) ? " a prime number" : " not a prime number"));
Printed the same with interpolation sir

2023-08-23 04:35 UTC, ravin-imm approved these changes

2023-08-23 04:35 UTC, closed without merging