T06
dineshN52/Training1 pull request #4
Opened 2023-08-21 03:19 UTC by dineshN52

2023-08-21 04:52 UTC, ravin-imm requested changes

2023-08-21 04:52 UTC, ravin-imm commented on Program.cs
> +         while (left < right) {
This is not correct. In the while loop you are checking if the left char is less than the right. When I check with "Madan" as the input, the application crashes. Please check.

2023-08-21 05:36 UTC, dineshN52 commented on Program.cs
> +         while (left < right) {
I have made changes in the comparison sir, Instead of direct character comparison, converted to int and compared.

2023-08-22 04:37 UTC, ravin-imm requested changes

2023-08-22 04:37 UTC, ravin-imm commented on Program.cs
> +         int right = input.Length - 1;
This can be simplified:
int left = 0, right = input.Length - 1;

2023-08-22 04:37 UTC, ravin-imm commented on Program.cs
> +            Console.WriteLine ("Given input is not a palindrome.");
Can you simplify it using a ternary conditional operator (?:) 
Use MSDN for more details.

2023-08-22 05:25 UTC, dineshN52 commented on Program.cs
> +         int right = input.Length - 1;
Simplified and updated sir

2023-08-22 05:25 UTC, dineshN52 commented on Program.cs
> +            Console.WriteLine ("Given input is not a palindrome.");
Ternary operator was introduced and updated

2023-08-23 04:09 UTC, ravin-imm requested changes

2023-08-23 04:09 UTC, ravin-imm commented on Program.cs
> +         Console.WriteLine (string.Concat ($"{input}, is", IsPalindrome (input) ? " a palindrome." : " not a palindrome."));
Try to do this without string.Concat (..)

2023-08-23 04:38 UTC, dineshN52 commented on Program.cs
> +         Console.WriteLine (string.Concat ($"{input}, is", IsPalindrome (input) ? " a palindrome." : " not a palindrome."));
Replaced with string interpolation sir

2023-08-23 04:39 UTC, ravin-imm approved these changes

2023-08-23 04:39 UTC, closed without merging