T01
dineshN52/Training1 pull request #5
Opened 2023-08-24 05:20 UTC by dineshN52

Number conversion game updated

2023-08-24 06:53 UTC, ravin-imm requested changes

2023-08-24 06:53 UTC, ravin-imm commented on Program.cs
> +         string binary = Convert.ToString (deci, 2);// Convert to binary
Can you implement this without using the above methods?

2023-08-28 04:27 UTC, ravin-imm requested changes

2023-08-28 04:27 UTC, ravin-imm commented on Program.cs
> +            hex = GetHexDigit (remainder) + hex;
This can be simplified further as:
**_hex += GetHexDigit (value % 16);_**
Please make the necessary such changes wherever required.

2023-08-28 04:32 UTC, dineshN52 commented on Program.cs
> +            hex = GetHexDigit (remainder) + hex;
Operator changed and updated sir

2023-08-28 04:35 UTC, ravin-imm requested changes

2023-08-28 04:35 UTC, ravin-imm commented on Program.cs
> +            hex += GetHexDigit (remainder);
This can be simplified further as _remainder_ variable is not used further:
_**hex += GetHexDigit (value % 16)**_

2023-08-28 05:21 UTC, ravin-imm approved these changes

2023-08-28 05:22 UTC, closed without merging